name: CI

on: [push, pull_request]

jobs:
  

    SpringBoot:
      name: SpringBoot
      runs-on: ubuntu-18.04
      defaults:
        run:
          working-directory: flipPhone


      steps:
        - name: Setup MySQL
          uses: samin/mysql-action@v1
          with:
            mysql database: 'db_example' # Optional, default value is "test". The specified database which will be create
            mysql user: 'springuser' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Of course you can use secrets, too
            mysql password: 'ThePassword' # Required if "mysql user" exists. The password for the "mysql user"
        - uses: actions/checkout@v1  
        - name: Setup java
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Set up Maven
          uses: stCarolas/setup-maven@v3
          with:
            maven-version: 3.5.4
        - name: run testes SpringBoot 
          run: mvn test
        - name: run SpringBoot
          run: mvn -B package --file pom.xml -Dmaven.test.skip=true
     

    
  
  
    Flutter:
      name: Flutter
      runs-on: ubuntu-18.04
      defaults:
        run:
          working-directory: flipphone_app
      steps:
        - uses: actions/checkout@v1
        - name: Setup java
          uses: actions/setup-java@v1
          with:
            java-version: '11.x'
        - name: Setup Flutter
          uses: subosito/flutter-action@v1
          with:
           flutter-version: '1.19.x'
           channel: 'dev'
        - name: get the dependencies
          run: flutter pub get
      #  - name: run testes Flutter
      #    run: flutter test --coverage
        - name: run app Flutter
          run: flutter build apk

