name: CI

on: [push, pull_request]

jobs:
  
  Flutter:
    name: Flutter
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: flipphone_app
        
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
         flutter-version: '1.12.x'
      - name: get the dependencies
        run: flutter pub get
      - name: run testes Flutter
        run: flutter test
      - name: run app Flutter
        run: flutter build apk
