name: CI

on: [push, pull_request]

jobs:
  
  SpringBoot:
    name: SpringBoot
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: flipPhone
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: run testes SpringBoot 
        run: mvn test
      - name: run SpringBoot
        run: mvn spring-boot:run
     
    
  
